version: '3'
services:
  mininet:
    build: .
    image: quanghong/mininet:ubuntu-22.04
    network_mode: "bridge"
    environment:
     - DISPLAY
    volumes:
     - /tmp/.X11-unix:/tmp/.X11-unix
     - /lib/modules:/lib/modules
    privileged: true
    tty: true
